using System;
using System.Threading;
using NUnit.Framework;
using Rebus.Activation;
using Rebus.Compression;
using Rebus.Config;
using Rebus.Tests.Extensions;
using Rebus.Transport.InMem;

namespace Rebus.Tests.Compression
{
    [TestFixture]
    public class TestCompressionIntegration : FixtureBase
    {
        [TestCase(true)]
        [TestCase(false)]
        public void ItWorks(bool withCompressionEnabled)
        {
            var activator = new BuiltinHandlerActivator();
            var gotIt = new ManualResetEvent(false);

            activator.Handle<string>(async str =>
            {
                if (string.Equals(str, LongText))
                {
                    gotIt.Set();
                }
                else
                {
                    throw new Exception(string.Format("Received text with {0} chars did not match expected text with {1} chars!",
                        str.Length, LongText.Length));
                }
            });

            Using(activator);

            var bus = Configure.With(activator)
                .Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "compressor"))
                .Options(o =>
                {
                    if (withCompressionEnabled)
                    {
                        o.EnableCompression(128);
                    }
                })
                .Start();

            bus.SendLocal(LongText).Wait();

            gotIt.WaitOrDie(TimeSpan.FromSeconds(10));
        }

        const string LongText = @"hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....

hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....

hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....

hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....
hooloo boolooo hvasså der lang tekst mange gentagelser helt sikker over 128 bytes....";
    }
}